Travel1/Airbnb/Airbnb/Controllers/ChiteitPhongController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Airbnb.Controllers
{
    public class ChiteitPhongController : Controller
    {
        // GET: ChiteitPhong
        public ActionResult Index()
        {
            return View();
        }

        // GET: ChiteitPhong/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: ChiteitPhong/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: ChiteitPhong/Create
        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: ChiteitPhong/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: ChiteitPhong/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: ChiteitPhong/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: ChiteitPhong/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

Travel1/Airbnb/Airbnb/Controllers/KetquaSearchController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Airbnb.Controllers
{
    public class KetquaSearchController : Controller
    {
        // GET: KetquaSearch
        public ActionResult Index()
        {
            return View();
        }

        // GET: KetquaSearch/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: KetquaSearch/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: KetquaSearch/Create
        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: KetquaSearch/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: KetquaSearch/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: KetquaSearch/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: KetquaSearch/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

Travel1/Airbnb/Airbnb/Views/KetquaSearch/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_MainLayout.cshtml";
}

<div class="hero-wrap" style="background-image: url('/Asset/images/bg_1.jpg');">
    <div class="overlay"></div>
    <div class="container">
        <div class="row no-gutters slider-text d-flex align-itemd-end justify-content-center">
            <div class="col-md-9 ftco-animate text-center d-flex align-items-end justify-content-center">

            </div>
        </div>
    </div>
</div>

<section class="ftco-section bg-light">
    <div class="container">
        <div class="row">
            <div class="col-lg-9">
                <div class="row">
                    <div class="col-sm col-md-6 col-lg-4 ftco-animate">
                        <div class="room">
                            <a href="@Url.Action("Index","ChiteitPhong")" class="img d-flex justify-content-center align-items-center" style="background-image: url('/Asset/images/img1/27.jpg');">
                                <div class="icon d-flex justify-content-center align-items-center">
                                    <span class="icon-search2"></span>
                                </div>
                            </a>
                            <div class="text p-3 text-center">
                                <h3 class="mb-3"><a href="rooms-single.html">Vườn Mây Dalaty</a></h3>
                                <p><span class="price mr-2">$120.00</span> <span class="per">/night</span></p>
                                <ul class="list">
                                    <li><span>Max:</span> 3 Persons</li>
                                    <li><span>Size:</span> 45 m2</li>
                                    <li><span>View:</span> Sea View</li>
                                    <li><span>Bed:</span> 1</li>
                                </ul>
                                <hr>
                                <p class="pt-1"><a href="room-single.html" class="btn-custom">Book Now <span class="icon-long-arrow-right"></span></a></p>
                            </div>
                        </div>
                    </div>
                    <div class="col-sm col-md-6 col-lg-4 ftco-animate">
                        <div class="room">
                            <a href="rooms-single.html" class="img d-flex justify-content-center align-items-center" style="background-image: url('/Asset/images/img1/26.jpg');">
                                <div class="icon d-flex justify-content-center align-items-center">
                                    <span class="icon-search2"></span>
                                </div>
                            </a>
                            <div class="text p-3 text-center">
                                <h3 class="mb-3"><a href="rooms-single.html">Zen's Home</a></h3>
                                <p><span class="price mr-2">$20.00</span> <span class="per">/night</span></p>
                                <ul class="list">
                                    <li><span>Max:</span> 3 Persons</li>
                                    <li><span>Size:</span> 45 m2</li>
                                    <li><span>View:</span> Sea View</li>
                                    <li><span>Bed:</span> 1</li>
                                </ul>
                                <hr>
                                <p class="pt-1"><a href="room-single.html" class="btn-custom">Book Now <span class="icon-long-arrow-right"></span></a></p>
                            </div>
                        </div>
                    </div>
                    <div class="col-sm col-md-6 col-lg-4 ftco-animate">
                        <div class="room">
                            <a href="rooms-single.html" class="img d-flex justify-content-center align-items-center" style="background-image: url('/Asset/images/img1/25.jpg');">
                                <div class="icon d-flex justify-content-center align-items-center">
                                    <span class="icon-search2"></span>
                                </div>
                            </a>
                            <div class="text p-3 text-center">
                                <h3 class="mb-3"><a href="rooms-single.html">An An Homestay</a></h3>
                                <p><span class="price mr-2">$150.00</span> <span class="per">/night</span></p>
                                <ul class="list">
                                    <li><span>Max:</span> 5 Persons</li>
                                    <li><span>Size:</span> 45 m2</li>
                                    <li><span>View:</span> Sea View</li>
                                    <li><span>Bed:</span> 2</li>
                                </ul>
                                <hr>
                                <p class="pt-1"><a href="room-single.html" class="btn-custom">Book Now <span class="icon-long-arrow-right"></span></a></p>
                            </div>
                        </div>
                    </div>
                  
                </div>
            </div>
            <div class="col-lg-3 sidebar">
                <div class="sidebar-wrap bg-light ftco-animate">
                    <h3 class="heading mb-4">Advanced Search</h3>
                    <form action="#">
                        <div class="fields">
                            <div class="form-group">
                                <input type="text" id="checkin_date" class="form-control checkin_date" placeholder="Check In Date">
                            </div>
                            <div class="form-group">
                                <input type="text" id="checkin_date" class="form-control checkout_date" placeholder="Check Out Date">
                            </div>
                            <div class="form-group">
                                <div class="select-wrap one-third">
                                    <div class="icon"><span class="ion-ios-arrow-down"></span></div>
                                    <select name="" id="" class="form-control">
                                        <option value="">Loại Homestay</option>

                                        <option value="">Family Homestay</option>
                                        <option value="">Deluxe Homestay</option>
                                        <option value="">Classic Homestay</option>
                                        <option value="">Superior Homestay</option>
                                        <option value="">Luxury Homestay</option>
                                    </select>
                                </div>
                            </div>
                            <div class="form-group">
                                <div class="select-wrap one-third">
                                    <div class="icon"><span class="ion-ios-arrow-down"></span></div>
                                    <select name="" id="" class="form-control">
                                        <option value="">Loại dịch vụ</option>

                                        <option value="">Giặt sấy</option>
                                        <option value="">Wifi</option>
                                        <option value="">Tự nấu ăn</option>
                                        <option value="">Được mang vật nuôi</option>
                                        <option value="">Giữ xe</option>
                                        <option value="">Dọn phòng</option>
                                    </select>
                                </div>
                            </div>

                            <div class="form-group">
                                <div class="range-slider">
                                    <span>
                                        <input type="number" value="25000" min="0" max="120000" />	-
                                        <input type="number" value="50000" min="0" max="120000" />
                                    </span>
                                    <input value="1000" min="0" max="120000" step="500" type="range" />
                                    <input value="50000" min="0" max="120000" step="500" type="range" />
                                    </svg>
                                </div>
                            </div>
                            <div class="form-group">
                                <input type="submit" value="Search" class="btn btn-primary py-3 px-5">
                            </div>
                        </div>
                    </form>
                </div>
                <div class="sidebar-wrap bg-light ftco-animate">
                    <h3 class="heading mb-4">Star Rating</h3>
                    <form method="post" class="star-rating">
                        <div class="form-check">
                            <input type="checkbox" class="form-check-input" id="exampleCheck1">
                            <label class="form-check-label" for="exampleCheck1">
                                <p class="rate"><span><i class="icon-star"></i><i class="icon-star"></i><i class="icon-star"></i><i class="icon-star"></i><i class="icon-star"></i></span></p>
                            </label>
                        </div>
                        <div class="form-check">
                            <input type="checkbox" class="form-check-input" id="exampleCheck1">
                            <label class="form-check-label" for="exampleCheck1">
                                <p class="rate"><span><i class="icon-star"></i><i class="icon-star"></i><i class="icon-star"></i><i class="icon-star"></i><i class="icon-star-o"></i></span></p>
                            </label>
                        </div>
                        <div class="form-check">
                            <input type="checkbox" class="form-check-input" id="exampleCheck1">
                            <label class="form-check-label" for="exampleCheck1">
                                <p class="rate"><span><i class="icon-star"></i><i class="icon-star"></i><i class="icon-star"></i><i class="icon-star-o"></i><i class="icon-star-o"></i></span></p>
                            </label>
                        </div>
                        <div class="form-check">
                            <input type="checkbox" class="form-check-input" id="exampleCheck1">
                            <label class="form-check-label" for="exampleCheck1">
                                <p class="rate"><span><i class="icon-star"></i><i class="icon-star"></i><i class="icon-star-o"></i><i class="icon-star-o"></i><i class="icon-star-o"></i></span></p>
                            </label>
                        </div>
                        <div class="form-check">
                            <input type="checkbox" class="form-check-input" id="exampleCheck1">
                            <label class="form-check-label" for="exampleCheck1">
                                <p class="rate"><span><i class="icon-star"></i><i class="icon-star-o"></i><i class="icon-star-o"></i><i class="icon-star-o"></i><i class="icon-star-o"></i></span></p>
                            </label>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</section>