Travel1/Airbnb/Airbnb/Controllers/ThanhToanController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Airbnb.Controllers
{
    public class ThanhToanController : Controller
    {
        // GET: ThanhToan
        public ActionResult Index()
        {
            return View();
        }

        // GET: ThanhToan/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: ThanhToan/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: ThanhToan/Create
        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: ThanhToan/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: ThanhToan/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: ThanhToan/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: ThanhToan/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

Travel1/Airbnb/Airbnb/Controllers/ThongBaoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Airbnb.Controllers
{
    public class ThongBaoController : Controller
    {
        // GET: ThongBao
        public ActionResult Index()
        {
            return View();
        }

        // GET: ThongBao/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: ThongBao/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: ThongBao/Create
        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: ThongBao/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: ThongBao/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: ThongBao/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: ThongBao/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

Travel1/Airbnb/Airbnb/Views/ThanhToan/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_MainLayout.cshtml";
}



<div class="hero-wrap" style="background-image: url('/Asset/images/bg_1.jpg');">
    <div class="overlay"></div>
    <div class="container">
        <div class="row no-gutters slider-text d-flex align-itemd-end justify-content-center">
            <div class="col-md-9 ftco-animate text-center d-flex align-items-end justify-content-center">
                
            </div>
        </div>
    </div>
</div>






<section class="ftco-section">
    <div class="container">
        <div class="row">
            <div class="col-lg-8">
                <div class="sidebar-wrap bg-light ftco-animate" style="width: 600px; ">
                    <h3 class="heading mb-4">Thông tin Người thanh toán</h3>
                    <form action="#">
                        <div class="fields">
                            <div class="form-group">
                                <input type="text" class="form-control" placeholder="Hà Thụy Ngọc Khánh">
                            </div>
                            <div class="form-group">
                                <input type="text" class="form-control" placeholder="hakhanh1998@gmail.com">
                            </div>

                      
                        </div>
                    </form>
                </div>
                <div class="sidebar-wrap bg-light ftco-animate" style="width: 600px; ">
                    <h3 class="heading mb-4">Hình thức thanh toán</h3>
                    <form action="#">
                        <div class="fields">
                            <div class="form-group">

                                <input type="radio" name="thanhtoan" value="momo" style="height:20px; width:20px; vertical-align: middle;" /> &nbsp; Thanh toán bằng thẻ quốc tế Visa &nbsp;
                                <img src="~/Asset/images/visa.png" style="height:25px; width:25px;">
                            </div>
                            <div class="form-group">
                                <input type="radio" name="thanhtoan" value="momo" style="height:20px; width:20px; vertical-align: middle;" />  &nbsp; Thanh toán bằng thẻ quốc tế Master card  &nbsp;
                                <img src="~/Asset/images/mastercard.jpg" style="height:25px; width:25px;">
                            </div>
                            <div class="form-group">
                                <input type="radio" name="thanhtoan" value="momo" style="height:20px; width:20px; vertical-align: middle;" /> &nbsp; Thanh toán bằng thẻ JCB &nbsp;
                                <img src="~/Asset/images/Jmage.png" style="height:25px; width:25px;">
                            </div>
                            


                        </div>
                    </form>
                </div>


            </div> <!-- .col-md-8 -->
            <div class="col-lg-4 sidebar ftco-animate">
                <div class="sidebar-wrap bg-light ftco-animate" style="width: 400px; ">
                    <h3 class="heading mb-4">Thông tin hóa đơn</h3>
                    <form action="#">
                        <div class="fields">
                            <div class="form-group">
                                <label for="#">Họ tên</label>
                                <input type="text" class="form-control" placeholder="Hà Thụy Ngọc Khánh">
                            </div>
                            <div class="form-group">
                                <label for="#">Ngày Checkin</label>
                                <input type="text" class="form-control" placeholder="20/01/2020">
                            </div>
                            <div class="form-group">
                                <label for="#">Ngày Checkout</label>
                                <input type="text" class="form-control" placeholder="27/01/2020">
                            </div>
                            <div class="form-group">
                                <label for="#">Số lượng</label>
                                <input type="text" class="form-control" placeholder="6">
                            </div>
                            <p><span style="font-size:20px; " class="price mr-2"><strong>Tổng tiền: </strong></span> <span class="per" style="font-size:20px; "><strong>$20.00</strong></span></p>

                            <div class="form-group">
                                <input type="button" value="Thanh Toán" class="btn btn-primary py-3 px-5" onclick="location.href='@Url.Action("Index", "ThongBao")'">
                            </div>
                        </div>
                    </form>
                </div>

            </div>
        </div>
    </div>
</section>