Travel1/Airbnb/Airbnb/Controllers/ThanhToanController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Airbnb.Controllers
{
    public class ThanhToanController : Controller
    {
        // GET: ThanhToan
        public ActionResult Index()
        {
            return View();
        }

        // GET: ThanhToan/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: ThanhToan/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: ThanhToan/Create
        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: ThanhToan/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: ThanhToan/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: ThanhToan/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: ThanhToan/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

Travel1/Airbnb/Airbnb/Controllers/ThongTinDatPhongController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Airbnb.Controllers
{
    public class ThongTinDatPhongController : Controller
    {
        // GET: ThongTinDatPhong
        public ActionResult Index()
        {
            return View();
        }

        // GET: ThongTinDatPhong/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: ThongTinDatPhong/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: ThongTinDatPhong/Create
        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: ThongTinDatPhong/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: ThongTinDatPhong/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: ThongTinDatPhong/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: ThongTinDatPhong/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

Travel1/Airbnb/Airbnb/Views/ThongTinDatPhong/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_MainLayout.cshtml";
}

<div class="hero-wrap" style="background-image: url('/Asset/images/bg_1.jpg');">
    <div class="overlay"></div>
    <div class="container">
        <div class="row no-gutters slider-text d-flex align-itemd-end justify-content-center">
            <div class="col-md-9 ftco-animate text-center d-flex align-items-end justify-content-center">
                
            </div>
        </div>
    </div>
</div>






<section class="ftco-section">
    <div class="container">
        <div class="row">
            <div class="col-lg-8">
                <section class="ftco-section ftc-no-pb ftc-no-pt">
                    <div class="container">
                        <div class="row">
                            <div class="col-md-5 p-md-5 img img-2 img-3 d-flex justify-content-center align-items-center" style="background-image: url('/Asset/images/bg_2.jpg');">
                                <a href="https://vimeo.com/45830194" class="icon popup-vimeo d-flex justify-content-center align-items-center">
                                    <span class="icon-play"></span>
                                </a>

                            </div>
                            <div>
                                <div class="sidebar-wrap bg-light ftco-animate" style="width: 400px; ">
                                    <h3 class="heading mb-4">Thông tin đặt phòng</h3>
                                    <form action="#">
                                        <div class="fields">
                                            <div class="form-group">
                                                <label for="#">Họ tên</label>
                                                <input type="text" class="form-control" placeholder="Hà Thụy Ngọc Khánh">
                                            </div>
                                            <div class="form-group">
                                                <label for="#">Ngày Checkin</label>
                                                <input type="text" class="form-control" placeholder="20/01/2020">
                                            </div>
                                            <div class="form-group">
                                                <label for="#">Ngày Checkout</label>
                                                <input type="text" class="form-control" placeholder="27/01/2020">
                                            </div>
                                            <div class="form-group">
                                                <label for="#">Số lượng</label>
                                                <input type="text" class="form-control" placeholder="6">
                                            </div>
                                            
                                            <div class="form-group">
                                                <input type="button" value="Xác nhận" class="btn btn-primary py-3 px-5" onclick="location.href='@Url.Action("Index", "ThanhToan")'">
                                                
                                            </div>
                                        </div>
                                    </form>

                                </div>
                            </div>




                        </div>

                    </div>
                </section>

            </div> <!-- .col-md-8 -->
            <div class="col-lg-4 sidebar ftco-animate">



                <div class="sidebar-box ftco-animate">
                    <h3>Top-rated Places</h3>
                    <div class="block-21 mb-4 d-flex">
                        <a class="blog-img mr-4" style="background-image: url('/Asset/images/image_1.jpg');"></a>
                        <div class="text">
                            <h3 class="heading"><a href="#">Top1: The belluy valley - Đà lạt</a></h3>
                            <div class="meta">
                                <div><a href="#"><span class="icon-calendar"></span> July 12, 2018</a></div>
                                <div><a href="#"><span class="icon-person"></span> Admin</a></div>
                                <div><a href="#"><span class="icon-chat"></span> 19</a></div>
                            </div>
                        </div>
                    </div>
                    <div class="block-21 mb-4 d-flex">
                        <a class="blog-img mr-4" style="background-image: url('/Asset/images/image_2.jpg');"></a>
                        <div class="text">
                            <h3 class="heading"><a href="#">Top2: The deluna - Nha Trang</a></h3>
                            <div class="meta">
                                <div><a href="#"><span class="icon-calendar"></span> July 12, 2018</a></div>
                                <div><a href="#"><span class="icon-person"></span> Admin</a></div>
                                <div><a href="#"><span class="icon-chat"></span> 19</a></div>
                            </div>
                        </div>
                    </div>
                    <div class="block-21 mb-4 d-flex">
                        <a class="blog-img mr-4" style="background-image: url('/Asset/images/image_3.jpg');"></a>
                        <div class="text">
                            <h3 class="heading"><a href="#">Top3: Pop House - Đà nẵng</a></h3>
                            <div class="meta">
                                <div><a href="#"><span class="icon-calendar"></span> July 12, 2018</a></div>
                                <div><a href="#"><span class="icon-person"></span> Admin</a></div>
                                <div><a href="#"><span class="icon-chat"></span> 19</a></div>
                            </div>
                        </div>
                    </div>
                </div>

     

       
            </div>
        </div>
    </div>
</section>